from PIL import Image

img = Image.open('1.jpg')
img.save('1.webp', 'webp')
img = Image.open('2.jpg')
img.save('2.webp', 'webp')
img = Image.open('3.jpg')
img.save('3.webp', 'webp')
img = Image.open('4.jpg')
img.save('4.webp', 'webp')
img = Image.open('5.jpg')
img.save('5.webp', 'webp')
img = Image.open('6.jpg')
img.save('6.webp', 'webp')
img = Image.open('7.jpg')
img.save('7.webp', 'webp')
img = Image.open('8.jpg')
img.save('8.webp', 'webp')
img = Image.open('banner.jpg')
img.save('banner.webp', 'webp')
img = Image.open('slide1.jpg')
img.save('slide1.webp', 'webp')
img = Image.open('slide2.jpg')
img.save('slide2.webp', 'webp')
img = Image.open('slide3.jpg')
img.save('slide3.webp', 'webp')
img = Image.open('slide4.jpg')
img.save('slide4.webp', 'webp')